version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Pre build commands started...
      - echo npm install started.
      - npm
      - echo Finished installing packages.
  build:
    commands:
      - echo Generating build directory for react.
      - npm build
      - echo Finished generating build directory.

  post_build:
    commands:
      - echo Deploying to S3 started
      # copy the contents of /build to S3 bucket
      - aws s3 sync build s3://contrax-testing-deployment/ --delete --exclude 'index.html' --acl public-read --cache-control 'max-age=860000'
      - aws s3 sync build s3://contrax-testing-deployment/ --delete --exclude '*' --include 'index.html' --acl public-read --cache-control 'max-age=0'
      - aws cloudfront create-invalidation --distribution-id E11MSFUDYDTFI0 --paths '/*'
      - echo Deploying to S3 finsihed

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
