version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre build commands started...
      - echo npm install started.
      - npm install --force
      - echo Finished installing packages.
  build:
    commands:
      - echo Generating build directory for react.
      - npm run build 
      - echo Finished generating build directory.

  post_build:
    commands:
      - echo Deploying to S3 started
      # copy the contents of /build to S3 bucket
      - aws s3 sync build s3://staging.contrax.finance/ --delete --exclude 'index.html' --acl public-read --cache-control 'max-age=860000'
      - aws s3 sync build s3://staging.contrax.finance/ --delete --exclude '*' --include 'index.html' --acl public-read --cache-control 'max-age=0'
      - aws cloudfront create-invalidation --distribution-id E2XNXLB83HJW1Z --paths '/*'
      - echo Deploying to S3 finsihed

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
  

  
  
  
  
